export interface Pilgrim {
  id: string;
  name: string;
  nameAr?: string;
  nationality: string;
  nationalityCode: string;
  passportNumber: string;
  passportExpiry: string;
  passportStatus: 'scanned' | 'verified' | 'missing' | 'pending';
  visaStatus: 'approved' | 'pending' | 'rejected' | 'processing' | 'not-started';
  visaNumber?: string;
  visaExpiry?: string;
  flightStatus: 'confirmed' | 'pending' | 'not-assigned';
  flightNumber?: string;
  flightDate?: string;
  hotelMakkah?: string;
  hotelMadinah?: string;
  roomNumber?: string;
  roomType?: 'single' | 'double' | 'triple' | 'quad';
  busNumber?: number;
  seatNumber?: string;
  groupId: string;
  groupLeader: string;
  paymentTotal: number;
  paymentPaid: number;
  paymentStatus: 'paid' | 'partial' | 'overdue' | 'pending';
  gender: 'M' | 'F';
  dateOfBirth: string;
  phone: string;
  email: string;
  emergencyContact: string;
  emergencyPhone: string;
  mahramId?: string;
  attendanceStatus: 'present' | 'absent' | 'not-checked';
  registeredAt: string;
  age: number;
}

export const pilgrims: Pilgrim[] = [
  {
    id: 'PIL-001',
    name: 'Ahmad Yusuf Al-Rashidi',
    nationality: 'Saudi Arabia',
    nationalityCode: 'SA',
    passportNumber: 'SA7823641',
    passportExpiry: '15/03/2029',
    passportStatus: 'verified',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88341',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'SV-881',
    flightDate: '15/09/2027',
    hotelMakkah: 'Hilton Suites Makkah',
    hotelMadinah: 'Anwar Al Madinah',
    roomNumber: '412',
    roomType: 'double',
    busNumber: 3,
    seatNumber: 'B7',
    groupId: 'GRP-001',
    groupLeader: 'Sheikh Ahmed Al-Rashidi',
    paymentTotal: 18500,
    paymentPaid: 18500,
    paymentStatus: 'paid',
    gender: 'M',
    dateOfBirth: '12/06/1975',
    age: 52,
    phone: '+966-55-123-4567',
    email: 'ahmad.rashidi@email.com',
    emergencyContact: 'Fatima Al-Rashidi',
    emergencyPhone: '+966-55-987-6543',
    attendanceStatus: 'present',
    registeredAt: '2026-03-15',
  },
  {
    id: 'PIL-002',
    name: 'Fatima Zahra Benali',
    nationality: 'Morocco',
    nationalityCode: 'MA',
    passportNumber: 'MA4561237',
    passportExpiry: '22/07/2028',
    passportStatus: 'verified',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88342',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'SV-881',
    flightDate: '15/09/2027',
    hotelMakkah: 'Hilton Suites Makkah',
    hotelMadinah: 'Anwar Al Madinah',
    roomNumber: '413',
    roomType: 'double',
    busNumber: 3,
    seatNumber: 'B8',
    groupId: 'GRP-001',
    groupLeader: 'Sheikh Ahmed Al-Rashidi',
    paymentTotal: 16800,
    paymentPaid: 16800,
    paymentStatus: 'paid',
    gender: 'F',
    dateOfBirth: '08/03/1978',
    age: 49,
    phone: '+212-661-234-567',
    email: 'fatima.benali@email.com',
    emergencyContact: 'Youssef Benali',
    emergencyPhone: '+212-661-987-654',
    mahramId: 'PIL-001',
    attendanceStatus: 'present',
    registeredAt: '2026-03-15',
  },
  {
    id: 'PIL-003',
    name: 'Mohammad Idris Patel',
    nationality: 'Pakistan',
    nationalityCode: 'PK',
    passportNumber: 'PK9934521',
    passportExpiry: '10/11/2027',
    passportStatus: 'scanned',
    visaStatus: 'processing',
    flightStatus: 'pending',
    hotelMakkah: 'Swissotel Makkah',
    hotelMadinah: undefined,
    roomNumber: '218',
    roomType: 'triple',
    busNumber: 7,
    seatNumber: 'C3',
    groupId: 'GRP-002',
    groupLeader: 'Sheikh Tariq Hussain',
    paymentTotal: 14200,
    paymentPaid: 9940,
    paymentStatus: 'partial',
    gender: 'M',
    dateOfBirth: '30/09/1965',
    age: 62,
    phone: '+92-312-456-7890',
    email: 'm.patel@email.com',
    emergencyContact: 'Aisha Patel',
    emergencyPhone: '+92-312-098-7654',
    attendanceStatus: 'not-checked',
    registeredAt: '2026-04-02',
  },
  {
    id: 'PIL-004',
    name: 'Nadia Okonkwo',
    nationality: 'Nigeria',
    nationalityCode: 'NG',
    passportNumber: 'NG8821043',
    passportExpiry: '05/08/2030',
    passportStatus: 'verified',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88390',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'SV-903',
    flightDate: '16/09/2027',
    hotelMakkah: 'Swissotel Makkah',
    hotelMadinah: 'Oberoi Madinah',
    roomNumber: '305',
    roomType: 'double',
    busNumber: 5,
    seatNumber: 'A12',
    groupId: 'GRP-003',
    groupLeader: 'Sheikh Ibrahim Musa',
    paymentTotal: 19200,
    paymentPaid: 19200,
    paymentStatus: 'paid',
    gender: 'F',
    dateOfBirth: '14/02/1982',
    age: 45,
    phone: '+234-803-456-7890',
    email: 'nadia.okonkwo@email.com',
    emergencyContact: 'Emeka Okonkwo',
    emergencyPhone: '+234-803-098-7654',
    attendanceStatus: 'present',
    registeredAt: '2026-02-20',
  },
  {
    id: 'PIL-005',
    name: 'Khalid Mansour Al-Otaibi',
    nationality: 'Kuwait',
    nationalityCode: 'KW',
    passportNumber: 'KW3312984',
    passportExpiry: '20/01/2028',
    passportStatus: 'missing',
    visaStatus: 'not-started',
    flightStatus: 'not-assigned',
    busNumber: undefined,
    seatNumber: undefined,
    roomNumber: undefined,
    groupId: 'GRP-004',
    groupLeader: 'Sheikh Faisal Al-Mutairi',
    paymentTotal: 17500,
    paymentPaid: 5250,
    paymentStatus: 'overdue',
    gender: 'M',
    dateOfBirth: '25/11/1971',
    age: 56,
    phone: '+965-9988-7766',
    email: 'khalid.otaibi@email.com',
    emergencyContact: 'Maryam Al-Otaibi',
    emergencyPhone: '+965-9988-5544',
    attendanceStatus: 'absent',
    registeredAt: '2026-05-10',
  },
  {
    id: 'PIL-006',
    name: 'Amira Hassan Saleh',
    nationality: 'Egypt',
    nationalityCode: 'EG',
    passportNumber: 'EG6654321',
    passportExpiry: '12/06/2029',
    passportStatus: 'verified',
    visaStatus: 'pending',
    flightStatus: 'pending',
    hotelMakkah: 'Hilton Suites Makkah',
    roomNumber: '501',
    roomType: 'single',
    busNumber: 2,
    seatNumber: 'D5',
    groupId: 'GRP-001',
    groupLeader: 'Sheikh Ahmed Al-Rashidi',
    paymentTotal: 15600,
    paymentPaid: 7800,
    paymentStatus: 'partial',
    gender: 'F',
    dateOfBirth: '03/07/1990',
    age: 37,
    phone: '+20-100-234-5678',
    email: 'amira.saleh@email.com',
    emergencyContact: 'Hassan Saleh',
    emergencyPhone: '+20-100-876-5432',
    attendanceStatus: 'not-checked',
    registeredAt: '2026-04-18',
  },
  {
    id: 'PIL-007',
    name: 'Yusuf Abdullahi Musa',
    nationality: 'Sudan',
    nationalityCode: 'SD',
    passportNumber: 'SD7789012',
    passportExpiry: '08/09/2028',
    passportStatus: 'scanned',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88412',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'SV-881',
    flightDate: '15/09/2027',
    hotelMakkah: 'Mövenpick Hajar Tower',
    hotelMadinah: 'Anwar Al Madinah',
    roomNumber: '622',
    roomType: 'quad',
    busNumber: 11,
    seatNumber: 'A4',
    groupId: 'GRP-005',
    groupLeader: 'Sheikh Umar Al-Faruq',
    paymentTotal: 13400,
    paymentPaid: 13400,
    paymentStatus: 'paid',
    gender: 'M',
    dateOfBirth: '17/04/1968',
    age: 59,
    phone: '+249-912-345-678',
    email: 'yusuf.musa@email.com',
    emergencyContact: 'Khadija Musa',
    emergencyPhone: '+249-912-876-543',
    attendanceStatus: 'present',
    registeredAt: '2026-03-28',
  },
  {
    id: 'PIL-008',
    name: 'Zainab Bint Abdullah',
    nationality: 'Indonesia',
    nationalityCode: 'ID',
    passportNumber: 'ID5523419',
    passportExpiry: '30/04/2027',
    passportStatus: 'pending',
    visaStatus: 'rejected',
    flightStatus: 'not-assigned',
    groupId: 'GRP-006',
    groupLeader: 'Sheikh Rizal Hakim',
    paymentTotal: 12800,
    paymentPaid: 12800,
    paymentStatus: 'paid',
    gender: 'F',
    dateOfBirth: '22/12/1985',
    age: 42,
    phone: '+62-812-345-6789',
    email: 'zainab.abdullah@email.com',
    emergencyContact: 'Abdullah Suharto',
    emergencyPhone: '+62-812-987-6543',
    attendanceStatus: 'absent',
    registeredAt: '2026-02-14',
  },
  {
    id: 'PIL-009',
    name: 'Ibrahim Al-Tunisi',
    nationality: 'Tunisia',
    nationalityCode: 'TN',
    passportNumber: 'TN8834521',
    passportExpiry: '14/08/2030',
    passportStatus: 'verified',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88445',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'SV-903',
    flightDate: '16/09/2027',
    hotelMakkah: 'Mövenpick Hajar Tower',
    hotelMadinah: 'Oberoi Madinah',
    roomNumber: '711',
    roomType: 'double',
    busNumber: 9,
    seatNumber: 'C11',
    groupId: 'GRP-005',
    groupLeader: 'Sheikh Umar Al-Faruq',
    paymentTotal: 16200,
    paymentPaid: 16200,
    paymentStatus: 'paid',
    gender: 'M',
    dateOfBirth: '05/01/1973',
    age: 54,
    phone: '+216-22-345-678',
    email: 'ibrahim.tunisi@email.com',
    emergencyContact: 'Leila Al-Tunisi',
    emergencyPhone: '+216-22-876-543',
    attendanceStatus: 'present',
    registeredAt: '2026-03-01',
  },
  {
    id: 'PIL-010',
    name: 'Maryam Koné',
    nationality: 'Senegal',
    nationalityCode: 'SN',
    passportNumber: 'SN2298734',
    passportExpiry: '18/02/2029',
    passportStatus: 'scanned',
    visaStatus: 'processing',
    flightStatus: 'pending',
    hotelMakkah: 'Hilton Suites Makkah',
    roomNumber: undefined,
    busNumber: undefined,
    groupId: 'GRP-007',
    groupLeader: 'Sheikh Moussa Diallo',
    paymentTotal: 14900,
    paymentPaid: 11175,
    paymentStatus: 'partial',
    gender: 'F',
    dateOfBirth: '09/10/1980',
    age: 47,
    phone: '+221-77-234-5678',
    email: 'maryam.kone@email.com',
    emergencyContact: 'Mamadou Koné',
    emergencyPhone: '+221-77-876-5432',
    attendanceStatus: 'not-checked',
    registeredAt: '2026-04-25',
  },
  {
    id: 'PIL-011',
    name: 'Abdulrahman Siddiqui',
    nationality: 'Bangladesh',
    nationalityCode: 'BD',
    passportNumber: 'BD7712398',
    passportExpiry: '25/05/2028',
    passportStatus: 'verified',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88501',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'BG-201',
    flightDate: '17/09/2027',
    hotelMakkah: 'Swissotel Makkah',
    hotelMadinah: 'Anwar Al Madinah',
    roomNumber: '318',
    roomType: 'quad',
    busNumber: 12,
    seatNumber: 'D9',
    groupId: 'GRP-008',
    groupLeader: 'Sheikh Noor Islam',
    paymentTotal: 11600,
    paymentPaid: 11600,
    paymentStatus: 'paid',
    gender: 'M',
    dateOfBirth: '14/07/1963',
    age: 64,
    phone: '+880-171-234-5678',
    email: 'abdulrahman.s@email.com',
    emergencyContact: 'Rahima Siddiqui',
    emergencyPhone: '+880-171-876-5432',
    attendanceStatus: 'present',
    registeredAt: '2026-02-28',
  },
  {
    id: 'PIL-012',
    name: 'Sumayyah Al-Ghamdi',
    nationality: 'Saudi Arabia',
    nationalityCode: 'SA',
    passportNumber: 'SA9912345',
    passportExpiry: '01/12/2030',
    passportStatus: 'verified',
    visaStatus: 'approved',
    visaNumber: 'VZ-2027-88512',
    visaExpiry: '30/10/2027',
    flightStatus: 'confirmed',
    flightNumber: 'SV-881',
    flightDate: '15/09/2027',
    hotelMakkah: 'Hilton Suites Makkah',
    hotelMadinah: 'Anwar Al Madinah',
    roomNumber: '414',
    roomType: 'double',
    busNumber: 1,
    seatNumber: 'A3',
    groupId: 'GRP-001',
    groupLeader: 'Sheikh Ahmed Al-Rashidi',
    paymentTotal: 18500,
    paymentPaid: 18500,
    paymentStatus: 'paid',
    gender: 'F',
    dateOfBirth: '19/08/1988',
    age: 39,
    phone: '+966-56-234-5678',
    email: 'sumayyah.ghamdi@email.com',
    emergencyContact: 'Abdullah Al-Ghamdi',
    emergencyPhone: '+966-56-876-5432',
    attendanceStatus: 'present',
    registeredAt: '2026-01-10',
  },
];

export interface GroupLeader {
  id: string;
  name: string;
  phone: string;
  groupId: string;
  pilgrimCount: number;
  visaApproved: number;
  passportVerified: number;
  paymentComplete: number;
  attendancePresent: number;
}

export const groupLeaders: GroupLeader[] = [
  { id: 'GL-001', name: 'Sheikh Ahmed Al-Rashidi', phone: '+966-50-111-2222', groupId: 'GRP-001', pilgrimCount: 47, visaApproved: 44, passportVerified: 46, paymentComplete: 38, attendancePresent: 41 },
  { id: 'GL-002', name: 'Sheikh Tariq Hussain', phone: '+92-300-222-3333', groupId: 'GRP-002', pilgrimCount: 52, visaApproved: 39, passportVerified: 48, paymentComplete: 31, attendancePresent: 45 },
  { id: 'GL-003', name: 'Sheikh Ibrahim Musa', phone: '+234-802-333-4444', groupId: 'GRP-003', pilgrimCount: 38, visaApproved: 38, passportVerified: 38, paymentComplete: 35, attendancePresent: 36 },
  { id: 'GL-004', name: 'Sheikh Faisal Al-Mutairi', phone: '+965-9977-5566', groupId: 'GRP-004', pilgrimCount: 41, visaApproved: 28, passportVerified: 33, paymentComplete: 22, attendancePresent: 30 },
  { id: 'GL-005', name: 'Sheikh Umar Al-Faruq', phone: '+249-911-444-555', groupId: 'GRP-005', pilgrimCount: 63, visaApproved: 61, passportVerified: 63, paymentComplete: 58, attendancePresent: 59 },
  { id: 'GL-006', name: 'Sheikh Rizal Hakim', phone: '+62-811-555-6666', groupId: 'GRP-006', pilgrimCount: 55, visaApproved: 42, passportVerified: 50, paymentComplete: 48, attendancePresent: 47 },
  { id: 'GL-007', name: 'Sheikh Moussa Diallo', phone: '+221-76-666-7777', groupId: 'GRP-007', pilgrimCount: 29, visaApproved: 21, passportVerified: 26, paymentComplete: 19, attendancePresent: 24 },
  { id: 'GL-008', name: 'Sheikh Noor Islam', phone: '+880-172-777-8888', groupId: 'GRP-008', pilgrimCount: 44, visaApproved: 44, passportVerified: 44, paymentComplete: 44, attendancePresent: 42 },
];

export const campaignStats = {
  totalPilgrims: 850,
  capacity: 900,
  visaApproved: 672,
  visaPending: 118,
  visaProcessing: 43,
  visaRejected: 17,
  passportVerified: 731,
  passportScanned: 64,
  passportMissing: 22,
  passportPending: 33,
  paymentFull: 541,
  paymentPartial: 219,
  paymentOverdue: 61,
  paymentPending: 29,
  totalRevenue: 14287500,
  collectedRevenue: 10923000,
  busesTotal: 18,
  busesAllocated: 16,
  hotelsTotal: 12,
  flightsTotal: 6,
  roomsAllocated: 798,
  roomsTotal: 850,
  groupsTotal: 18,
  atRiskCount: 23,
  departureDate: '15/09/2027',
  returnDate: '22/10/2027',
};

export const atRiskPilgrims = [
  { id: 'PIL-005', name: 'Khalid Mansour Al-Otaibi', issue: 'Passport missing + Visa not started', severity: 'critical' as const, daysToDepart: 12 },
  { id: 'PIL-008', name: 'Zainab Bint Abdullah', issue: 'Visa rejected — appeal required', severity: 'critical' as const, daysToDepart: 13 },
  { id: 'PIL-023', name: 'Hassan Boudiaf', issue: 'Passport expires before return date', severity: 'high' as const, daysToDepart: 12 },
  { id: 'PIL-047', name: 'Rania Al-Sayed', issue: 'Payment 30% — overdue SAR 10,850', severity: 'high' as const, daysToDepart: 12 },
  { id: 'PIL-112', name: 'Bilal Osman Farah', issue: 'No bus/room allocation assigned', severity: 'medium' as const, daysToDepart: 12 },
  { id: 'PIL-198', name: 'Tariq Noor Al-Din', issue: 'Flight not confirmed — seat unassigned', severity: 'medium' as const, daysToDepart: 13 },
];

export const recentActivity = [
  { id: 'ACT-001', type: 'visa', message: 'Visa approved for Ahmad Yusuf Al-Rashidi (PIL-001)', time: '8 min ago', icon: 'check' },
  { id: 'ACT-002', type: 'payment', message: 'Payment received SAR 9,940 from Mohammad Patel (PIL-003)', time: '23 min ago', icon: 'payment' },
  { id: 'ACT-003', type: 'passport', message: 'Passport scanned for 12 pilgrims in Group GRP-006', time: '1 hr ago', icon: 'scan' },
  { id: 'ACT-004', type: 'alert', message: 'Visa rejected for Zainab Bint Abdullah (PIL-008) — action required', time: '2 hr ago', icon: 'alert' },
  { id: 'ACT-005', type: 'allocation', message: 'Bus #7 seating plan updated — 48/50 seats filled', time: '3 hr ago', icon: 'bus' },
  { id: 'ACT-006', type: 'whatsapp', message: 'WhatsApp broadcast sent to Group GRP-001 (47 recipients)', time: '4 hr ago', icon: 'message' },
  { id: 'ACT-007', type: 'checkin', message: 'QR check-in completed for 38 pilgrims — Group GRP-003', time: '5 hr ago', icon: 'qr' },
  { id: 'ACT-008', type: 'visa', message: 'Visa processing initiated for 43 pilgrims via MOFA portal', time: '6 hr ago', icon: 'processing' },
];

export const visaChartData = [
  { name: 'Approved', value: 672, fill: '#16A34A' },
  { name: 'Pending', value: 118, fill: '#D97706' },
  { name: 'Processing', value: 43, fill: '#2563EB' },
  { name: 'Rejected', value: 17, fill: '#DC2626' },
];

export const paymentChartData = [
  { name: 'Paid Full', value: 541, fill: '#1B6B4A' },
  { name: 'Partial', value: 219, fill: '#C5A028' },
  { name: 'Overdue', value: 61, fill: '#DC2626' },
  { name: 'Pending', value: 29, fill: '#6B6560' },
];

export const groupProgressData = [
  { group: 'GRP-001', leader: 'Sheikh Ahmed', pilgrims: 47, visa: 93.6, payment: 80.9, passport: 97.9 },
  { group: 'GRP-002', leader: 'Sheikh Tariq', pilgrims: 52, visa: 75.0, payment: 59.6, passport: 92.3 },
  { group: 'GRP-003', leader: 'Sheikh Ibrahim', pilgrims: 38, visa: 100, payment: 92.1, passport: 100 },
  { group: 'GRP-004', leader: 'Sheikh Faisal', pilgrims: 41, visa: 68.3, payment: 53.7, passport: 80.5 },
  { group: 'GRP-005', leader: 'Sheikh Umar', pilgrims: 63, visa: 96.8, payment: 92.1, passport: 100 },
  { group: 'GRP-006', leader: 'Sheikh Rizal', pilgrims: 55, visa: 76.4, payment: 87.3, passport: 90.9 },
  { group: 'GRP-007', leader: 'Sheikh Moussa', pilgrims: 29, visa: 72.4, payment: 65.5, passport: 89.7 },
  { group: 'GRP-008', leader: 'Sheikh Noor', pilgrims: 44, visa: 100, payment: 100, passport: 100 },
];

export const registrationTimelineData = [
  { month: 'Oct 26', count: 42 },
  { month: 'Nov 26', count: 78 },
  { month: 'Dec 26', count: 115 },
  { month: 'Jan 27', count: 167 },
  { month: 'Feb 27', count: 203 },
  { month: 'Mar 27', count: 241 },
  { month: 'Apr 27', count: 298 },
  { month: 'May 27', count: 341 },
  { month: 'Jun 27', count: 389 },
  { month: 'Jul 27', count: 421 },
  { month: 'Aug 27', count: 476 },
  { month: 'Sep 27', count: 850 },
];

export const buses = Array.from({ length: 18 }, (_, i) => ({
  id: `BUS-${String(i + 1).padStart(2, '0')}`,
  number: i + 1,
  capacity: 50,
  allocated: [48, 50, 46, 50, 44, 50, 48, 41, 50, 38, 50, 47, 50, 43, 50, 50, 36, 29][i],
  driver: ['Khalid Al-Harbi', 'Samir Nour', 'Faris Al-Zahrani', 'Rashid Mubarak', 'Tariq Al-Ghamdi', 'Omar Siddiq', 'Bilal Hassan', 'Nawaf Al-Otaibi', 'Zaid Al-Shammari', 'Majed Al-Dosari', 'Hani Al-Qahtani', 'Saad Al-Bishi', 'Nasser Al-Harbi', 'Fahad Al-Mutairi', 'Waleed Al-Rashidi', 'Sultan Al-Ghamdi', 'Turki Al-Shamrani', 'Bandar Al-Yami'][i],
  route: i < 9 ? 'Makkah Route A' : 'Makkah Route B',
  groupId: `GRP-00${(i % 8) + 1}`,
}));

export const hotels = [
  { id: 'HTL-001', name: 'Hilton Suites Makkah', city: 'Makkah', stars: 5, totalRooms: 120, allocatedRooms: 118, pilgrims: 287, checkIn: '15/09/2027', checkOut: '22/09/2027' },
  { id: 'HTL-002', name: 'Swissotel Makkah', city: 'Makkah', stars: 5, totalRooms: 85, allocatedRooms: 82, pilgrims: 198, checkIn: '15/09/2027', checkOut: '22/09/2027' },
  { id: 'HTL-003', name: 'Mövenpick Hajar Tower', city: 'Makkah', stars: 5, totalRooms: 70, allocatedRooms: 68, pilgrims: 162, checkIn: '15/09/2027', checkOut: '22/09/2027' },
  { id: 'HTL-004', name: 'Dar Al Tawhid', city: 'Makkah', stars: 4, totalRooms: 45, allocatedRooms: 43, pilgrims: 103, checkIn: '15/09/2027', checkOut: '22/09/2027' },
  { id: 'HTL-005', name: 'Anwar Al Madinah', city: 'Madinah', stars: 5, totalRooms: 95, allocatedRooms: 91, pilgrims: 221, checkIn: '22/09/2027', checkOut: '28/09/2027' },
  { id: 'HTL-006', name: 'Oberoi Madinah', city: 'Madinah', stars: 5, totalRooms: 60, allocatedRooms: 58, pilgrims: 142, checkIn: '22/09/2027', checkOut: '28/09/2027' },
  { id: 'HTL-007', name: 'Hilton Garden Madinah', city: 'Madinah', stars: 4, totalRooms: 55, allocatedRooms: 52, pilgrims: 128, checkIn: '22/09/2027', checkOut: '28/09/2027' },
  { id: 'HTL-008', name: 'Millennium Al Aqeeq', city: 'Madinah', stars: 4, totalRooms: 40, allocatedRooms: 37, pilgrims: 91, checkIn: '22/09/2027', checkOut: '28/09/2027' },
];

export const flights = [
  { id: 'FLT-001', flightNumber: 'SV-881', airline: 'Saudi Airlines', origin: 'Cairo (CAI)', destination: 'Jeddah (JED)', date: '15/09/2027', time: '08:30', passengers: 187, confirmed: 182, status: 'confirmed' as const },
  { id: 'FLT-002', flightNumber: 'SV-903', airline: 'Saudi Airlines', origin: 'Lagos (LOS)', destination: 'Jeddah (JED)', date: '16/09/2027', time: '14:15', passengers: 143, confirmed: 138, status: 'confirmed' as const },
  { id: 'FLT-003', flightNumber: 'BG-201', airline: 'Biman Bangladesh', origin: 'Dhaka (DAC)', destination: 'Jeddah (JED)', date: '17/09/2027', time: '22:00', passengers: 112, confirmed: 109, status: 'confirmed' as const },
  { id: 'FLT-004', flightNumber: 'PK-853', airline: 'Pakistan Int\'l', origin: 'Karachi (KHI)', destination: 'Jeddah (JED)', date: '17/09/2027', time: '03:45', passengers: 98, confirmed: 91, status: 'pending' as const },
  { id: 'FLT-005', flightNumber: 'GA-991', airline: 'Garuda Indonesia', origin: 'Jakarta (CGK)', destination: 'Jeddah (JED)', date: '18/09/2027', time: '11:30', passengers: 155, confirmed: 148, status: 'confirmed' as const },
  { id: 'FLT-006', flightNumber: 'TU-742', airline: 'Tunisair', origin: 'Tunis (TUN)', destination: 'Jeddah (JED)', date: '18/09/2027', time: '16:00', passengers: 155, confirmed: 141, status: 'pending' as const },
];